# https://circleci.com/docs/2.0/language-javascript/

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - v1-dependencies-{{ .Branch }}-
          - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn run build # build to avoid lint issues with missing files
      - run: yarn run lint
      - run: yarn run test-ci
      - run: yarn codecov

      - store_artifacts:
          path: test/coverage
          prefix: coverage
